#!/bin/bash

# HopeSwap - Clean up guest/anonymous data from Firebase
# This script helps remove any test or anonymous user data

echo "🧹 HopeSwap Firebase Cleanup Script"
echo "===================================="
echo ""
echo "This script will help you clean up guest/anonymous data from Firebase."
echo ""

# Check if Firebase CLI is installed
if ! command -v firebase &> /dev/null; then
    echo "❌ Firebase CLI is not installed."
    echo "Install it with: npm install -g firebase-tools"
    exit 1
fi

echo "📋 Steps to clean up data:"
echo ""
echo "1. Go to Firebase Console: https://console.firebase.google.com"
echo "2. Select your HopeSwap project"
echo "3. Navigate to Firestore Database"
echo "4. Look for documents with:"
echo "   - userId: 'anonymous' or empty"
echo "   - sellerUsername: 'Unknown seller' or 'Guest'"
echo "   - Items created before implementing authentication"
echo ""
echo "5. Delete these documents manually or run this query in Firebase Admin SDK:"
echo ""
echo "// Example cleanup code (run in a Node.js environment with Firebase Admin SDK):"
echo "const admin = require('firebase-admin');"
echo "admin.initializeApp();"
echo ""
echo "// Delete items with no proper userId"
echo "const db = admin.firestore();"
echo "const itemsRef = db.collection('items');"
echo ""
echo "// Find and delete anonymous items"
echo "itemsRef.where('sellerUsername', '==', 'Unknown seller').get()"
echo "  .then(snapshot => {"
echo "    snapshot.forEach(doc => {"
echo "      doc.ref.delete();"
echo "      console.log('Deleted:', doc.id);"
echo "    });"
echo "  });"
echo ""
echo "6. Also check Authentication tab for anonymous users and delete them"
echo ""
echo "🔒 Security Rules Update:"
echo "Update your Firestore rules to prevent anonymous writes:"
echo ""
echo "rules_version = '2';"
echo "service cloud.firestore {"
echo "  match /databases/{database}/documents {"
echo "    // Only authenticated users can read"
echo "    match /{document=**} {"
echo "      allow read: if request.auth != null;"
echo "    }"
echo "    "
echo "    // Only authenticated non-anonymous users can write"
echo "    match /items/{itemId} {"
echo "      allow write: if request.auth != null "
echo "        && request.auth.token.firebase.sign_in_provider != 'anonymous';"
echo "    }"
echo "    "
echo "    // Users can only modify their own items"
echo "    match /items/{itemId} {"
echo "      allow update, delete: if request.auth != null "
echo "        && request.auth.uid == resource.data.firebaseUserId;"
echo "    }"
echo "  }"
echo "}"
echo ""
echo "✅ After cleanup, your app will only have authenticated user data!"